sudo: required
language: python 
services:
  - docker
addons:
  apt:
    packages:
      - docker-ce
python:
  - "3.6"
os:
  - linux
before_install:
  
  - sudo docker swarm init
install: 
  - pip install -r requirements.txt
script: 
  - sudo echo "DOCKER_OPTS=\"--registry-mirror=https://registry.docker-cn.com\" " >> /etc/default/docker
  - sudo service docker restart
  - docker --version
  - python manage.py test 
