sudo: required
language: python 
python:
  - "3.6"
services:
  - docker
os:
  - linux
before_install:
  - docker swarm init
install: 
  - pip install -r requirements.txt
script: 
  - python test.py  
