sudo: required
language: python 
addons:
  apt:
    packages:
      - docker-ce
python:
  - "3.6"
os:
  - linux
before_install:
  - docker swarm init
install: 
  - pip install -r requirements.txt
script: 
  - docker --version
  - python test.py  
