sudo: required
language: python 
python:
  - "3.6.5"
services:
  - docker
os:
  - osx
before_install:
  - docker swarm init
install: 
  - pip install -r requirements.txt
script: 
  - python manage.py test Promotion
