sudo: required
language: python 
services:
  - docker
addons:
  apt:
    packages:
      - docker-ce
python:
  - "3.6"
os:
  - linux
before_install:
  - sudo /usr/bin/dockerd --registry-mirror=https://registry.docker-cn.com --raw-logs
  - docker swarm init
install: 
  - pip install -r requirements.txt
script: 
  - docker --version
  - python manage.py test 
