language: python 
python:
  - "3.6.5"
services:
  - docker
before_install:
 - docker swarm init
env:
  - DJANGO_VERSION=2.0.5
install: 
  - pip install -r requirements.txt
script: 
  - python test.py
