sudo: required
language: python 
addons:
  apt:
    packages:
      - docker-ce
python:
  - "3.6"
os:
  - linux
before_install:
  - echo DOCKER_OPTS="--registry-mirror=https://registry.docker-cn.com" >> /etc/default/docker
  - service docker restart
  - docker swarm init
install: 
  - pip install -r requirements.txt
script: 
  - docker --version
  - python manage.py test 
